ENABLE_WAIT_RESULT=true
ALLOW_ENABLE_NETWORK=false
ENABLE_NETWORK=false
COUNT=2
MAX_QUEUE_SIZE=100
CPU_TIME_LIMIT=60
CPU_EXTRA_TIME=1
WALL_TIME_LIMIT=120
MEMORY_LIMIT=262144
STACK_LIMIT=65536
MAX_FILE_SIZE=1024
REDIS_HOST=redis
REDIS_PASSWORD=judge0_local_redis_password
POSTGRES_HOST=db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_local_postgres_password
